### ISSUE TITLE
no output file created

### ISSUE THREAD

**Issue by joqb** [vibansal/hapcut#1]
Hi,

I tried to run Hapcut on my data  as recommended in the readme file but there was never an outputfile created. 

Thanks,
Nath

Commands:
extractHAIRS --VCF consensus.vcf --bam raw.k4.R1R2.bam.sorted.bam  --maxIS 600 > fragment
HAPCUT --fragments fragment --VCF consensus.vcf --output result.fa --maxiter 10 --maxmem 12000 --longreads 1 > hapcut.log

PS: I tried with and without file extension for the output file

**Comment by vibansal** [comment]
Does the sample data create output files ? Can you check if the 'fragment' file was empty as well.

**Comment by marcelm** [comment]
I’m having the same problem. In my case, already the fragment file is empty. The reads are PacBio reads (a Genome in a Bottle dataset), but they do have quality values, so I have not used the `--noquality` option, which seems to have been specifically added for PacBio reads. Assuming it was still a problem with too low mapping or base qualities, I then added `--mbq 1 --mmq 1`, but the created file was still empty.

This is what the call to `extractHAIRS --VCF file.vcf --bam file.bam --mbq 1 --mmq 1 --out fragments.txt` prints:

```
 extracting haplotype informative reads from bamfiles file.bam minQV 1 minMQ 1 maxIS 1000 

VCF file file.vcf has 140744 variants 
vcffile file.vcf chromosomes 1 hetvariants 48023 140744
reading sorted bamfile file.bam 
```

The VCF file contains a single chromosome, and the number of heterozygous variants seems to be about correct, so VCF parsing seems to be fine.

**Comment by vibansal** [comment]
Please check that:
1. extracthairs generates non-empty file on sample data 
2. VCF file has same chromosome names as BAM file, e.g. chr1 vs 1

**Comment by marcelm** [comment]
Thanks for the quick reply.
1. Which sample data? [In the repository](https://github.com/vibansal/hapcut/master/testdata/), there is only a .fragments file, no BAM file, so I believe extractHAIRS does not need to be run on it.
2. The chromosome names match (it is "1" in both cases).

If you want to reproduce it, here is a way to generate a small test dataset from the publicly available Genome in a Bottle dataset:

```
bcftools view ftp://ftp-trace.ncbi.nlm.nih.gov/giab/ftp/data/AshkenazimTrio/analysis/NIST_CallsIn2Technologies_05182015/HG002-multiall-fullcombine.vcf.gz 1:9000000-10000000  > file.vcf
samtools view -b ftp://ftp-trace.ncbi.nlm.nih.gov/giab/ftp/data/AshkenazimTrio/HG002_NA24385_son/PacBio_MtSinai_NIST/MtSinai_blasr_bam_GRCh37/hg002_gr37_1.bam 1:9000000-10000000 > file.bam
```

As a disclaimer: I am trying to compare multiple phasing tools to each other. If hapCUT does not work in this particular case, it is not a problem. However, I also wanted to test HapTree, which requires the same input format as hapCUT and refers to the extractHAIRS tool for preprocessing BAM files. It would be nice if I could inclue both tools in my comparison.

**Comment by vibansal** [comment]
Thanks for providing the data. The BAM file that you shared contains the '=' operation in the cigar string which was not being processed by extracthairs. I have updated the code and run it successfully on the data. Let me know if there are any problems.

**Comment by marcelm** [comment]
Thanks a lot! I have tested it now and can confirm that both the extractHAIRS tool and hapCUT work fine, also on the full dataset. Also, the components it outputs seem to be of reasonable size.
