### ISSUE TITLE
Exit Status

### ISSUE THREAD

**Issue by yjqiu** [vibansal/hapcut#3]
Hi

I just run Hapcut and always get exit status 1，suggesting the jobs fails. But all the output seems to be fine. I checked the source code, and it seems that the program always return 1. Am I correct? And is there any specific reason for that?

Thanks,
Yunjiang

**Comment by vibansal** [comment]
Hi, I just updated the code. Can you check if you still get the error ?

**Comment by yjqiu** [comment]
Yes, it works fine. Thanks.

**Comment by yjqiu** [comment]
Sorry, but it seems to appear again somehow. And I checked the hapcut.c. It still return 1 at the end of main function as attached below.

if (flag !=3) // three essential arguments are not supplied 
    {  
        print_hapcut_options(); return 0;
    }  
    else
    {  
        if (VCFformat ==1) 
        {  
            fprintf(stderr,"\n\nfragment file: %s\nvariantfile (VCF format):%s\nhaplotypes will be output to file: %s\niterations of maxcut algorithm: %d\nQVoffset: %d\n\n
            maxcut_haplotyping(fragfile,VCFfile,0,hapfile,maxiter); 
        }  
        else 
        {  
            fprintf(stderr,"\n\nfragment file: %s\nvariantfile (variant format):%s\nhaplotypes will be output to file: %s\niterations of maxcut algorithm: %d\nQVoffset: %d
            maxcut_haplotyping(fragfile,varfile,0,hapfile,maxiter); 
        }  
    }  
    return 1;
}

**Comment by vibansal** [comment]
You can change that to return 0 (instead of 1) if it is causing problems. It has no importance for the program itself.

**Comment by yjqiu** [comment]
I just changed it and it works fine. I just want to make sure there is no side effect of that. Thank you so much!
